---
title: ""
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

# Set Up for Transcribing & Coding 1-Hour Natural Play

## Getting Started

1. **Download** the [development version of Datavyu](http://datavyu.org/download.html).
2. **Download** the *PLAY_CodingTemplate.opf* file from the [PLAY Databrary Volume](https://nyu.databrary.org/volume/254/slot/14924/-?asset=73892). Name this file with the PLAY naming convention (e.g., *PLAY_NYU001, … PLAY_NYU010, … PLAY_NYU030*).
    - This template contains all of the primary variables that will be coded by each site: communication, gesture, object interaction, locomotion, and emotion.
3. **Download** Ruby scripts for each coding variable as needed from the [PLAY Github repository](https://github.com/databrary/PLAY-Project-Datavyu-scripts).

## Get to Know Datavyu

1. Familiarize yourself with Datavyu before you begin coding (resources on Datavyu.org, videos from past workshops, etc.).
    - Refer to the [Datavyu User Guide](http://www.datavyu.org/user-guide/index.html).
    - Take a look at our [Best Practices for Coding Behavioral Data From Video](http://www.datavyu.org/user-guide/best-practices.html) on the Datavyu site.

## Coding in Passes

* The coding manual describes the transcription process and codes for 5 content areas: communication, gesture, object interaction, locomotion, and emotion.
* Each content area includes two passes: one pass for the infant and one pass for the mother. For gesture, the baby and mom are coded together in a single pass.
* A pass entails scoring the relevant codes for 1-hour of video.

Please visit our [GitHub Repository](https://github.com/databrary/PLAY-Project-Datavyu-scripts) for all of the scripts mentioned in this wiki.

## Workflow for Coding Communication Passes

1. After the file has been transcribed according to procedure in [Transcription](https://dev1.ed-projects.nyu.edu/wikis/docuwiki/doku.php/transcription), run two additional scripts that will prepare new [Communication](https://dev1.ed-projects.nyu.edu/wikis/docuwiki/doku.php/manual2) columns for further coding.
2. **Run** *splitmombaby_transcribe.rb*. This script pulls out mom and baby language from the _*transcribe*_ column into two new columns: (1) _*momspeech*_  and (2) _*babyvoc*_ . Each column is automatically populated with cells from the respectively tagged utterances from the _*transcribe*_  column (e.g., the script ports all utterances coded as ‘m’ to the _*momspeech*_  column and 'b' to the _*babyvoc*_  column). Each new cell in _*momspeech*_  and _*babyvoc*_  is a point cell created at the onset of each cell from the transcription.
3. **Run** *create_mombaby_utterancetype.rb*. This script also creates two new columns: (1) _*momutterancetype*_ and (2) _*babyutterancetype*_ . For each cell in _*momspeech*_  and _*babyvoc*_ , a new cell is created in _*momutterancetype*_  and _*babyutterancetype*_ , respectively. The codes for these cells are blank, and the coder now scores mom and baby communication according to definitions in [Communication Codes](https://dev1.ed-projects.nyu.edu/wikis/docuwiki/doku.php/manual2).

## Workflow for Coding Gesture Pass

1. Score baby and mom gesture together in a single pass according to definitions in [Gesture Codes](https://dev1.ed-projects.nyu.edu/wikis/docuwiki/doku.php/gesture).
2. After the _*gesture*_ coding pass (for both mom and baby) has been done, run a script that will separate mom and baby gestures into two columns.
3. **Run** *Split-MomBabyGesture.rb*. This script pulls out mom and baby gestures from the _*gesture*_ column into two new columns: (1) _*babygesture*_ and (2) _*momgesture*_. Each column is automatically populated with cells from the respectively tagged events from the _*gesture*_ column (e.g., the script ports all gestures coded as ‘m’ to the _*momgesture*_ column and 'b' to the _*babygesture*_ column). Each new cell in babygesture and momgesture is a point cell created at the onset of each cell in the _*gesture*_ column.

## Workflow for coding Object, Locomotion, and Emotion Passes

1. Choose whether to code baby or mom first within each pass for object, locomotion, or emotion.
2. Score each pass according to definitions in [Object Codes](https://dev1.ed-projects.nyu.edu/wikis/docuwiki/doku.php/manual3), [Locomotion Codes](https://dev1.ed-projects.nyu.edu/wikis/docuwiki/doku.php/manual4), or [Emotion Codes](https://dev1.ed-projects.nyu.edu/wikis/docuwiki/doku.php/emotion).

## Workflow for Inter-Observer Reliability on Communication, Gesture, Object, Locomotion, and Emotion Passes

1. After the primary coder finishes a pass: _*babyutterancetype*_, _*momutterancetype*_, _*gesture*_ (split into _*babygesture*_, _*momgesture*_), _*babyobject*_, _*momobject*_, _*babyloc*_, _*momloc*_, _*babyemotion*_, or _*momemotion*_ run two scripts to set up the Datavyu spreadsheet for coding reliability.
2. First, **run** a script called *insert-RelBlocks.rb*.
    - This script randomly generates 3, 5-minute chunks within the first, second, and third 20-minute sections of the 1-hour video of free play. By quasi-randomly inserting reliability blocks from areas of the primary coder’s pass, this will ensure that the reliability coder sees each portion of the video for each child’s session. Thus, the idiosyncrasies of each child, fluctuations over the 1-hour session, and drift in the coder are spread over the session.
    - Reliability on each coding pass is done on the same 3, 5-minute blocks for each pass.
    - The scripting window in Datavyu will prompt when everything has been successfully completed. You should now have a brand new column in your spreadsheet named _*reliability_blocks*_.
    - This script should only be run **once** so that reliability coding can be done within the same time frame for each coding domain for each session.
3. Now, **run** another script appropriate for the pass reliability needs to be coded on: *CreateReliability-BabyUtterancetype.rb* or *CreateReliability-MomUtterancetype.rb* or *CreateReliability-Gesture.rb* or *CreateReliability-MomBaby-Loc.rb* or *CreateReliability-MomBaby-Object.rb* OR *CreateReliability-MomBaby-Emotion.rb*
    - This script inserts new coding columns where your reliability coder will score the video while they are locked into the script-generated, 5-minute chunks in the _*reliability_blocks*_ column.