---
title: ''
---

## EARLY CHILDHOOD BEHAVIOR QUESTIONNAIRE (ECBQ) – VERY SHORT FORM (ROTHBART) 
INSTRUCTIONS: Please read carefully before starting. [PURPLE SCALE]

As you read each description of the child’s behavior below, please indicate how often the child did this during the last two weeks by circling one of the numbers in the right column. 
These numbers indicate how often you observed the behavior described during the last two weeks.
   
| never | rarely | less than half the time | about half the time | more than half the time | almost always | always | does not apply | 
|-|-|-|-|-|-|-|-|
| 1 | 2 | 3 | 4 | 5 | 6 | 7 | NA |


The “Does Not Apply” column (NA) is used when you did not see the child in the situation described during the last two weeks. 
For example, if the situation mentions the child going to the doctor and there was no time during the last two weeks when the child went to the doctor, circle the (NA) column. “Does Not Apply” (NA) is different from “NEVER” (1). 
“Never” is used when you saw the child in the situation but the child never engaged in the behavior mentioned in the last two weeks. 
Please be sure to circle a number or NA for every item.

In the last two weeks...

**When approached by an unfamiliar person in a public place (for example, the grocery store), how often did your child cling to a parent?**

**While having trouble completing a task (e.g., building, drawing, dressing), how often did your child get easily irritated?**

**When a familiar child came to your home, how often did your child seek out the company of the child?**

**When offered a choice of activities, how often did your child decide what to do very quickly and go after it?**

**During daily or evening quiet time with you and your child, how often did your child enjoy just being quietly sung to?**

**While playing outdoors, how often did your child choose to take chances for the fun and excitement of it?**

**When engaged in play with his/her favorite toy, how often did your child...**

- **...play for more than 10 minutes?**
- **...continue to play while at the same time responding to your remarks or questions?**

**When told that loved adults would visit, how often did your child get very excited?**

**During quiet activities, such as reading a story, how often did your child fiddle with his/her hair, clothing, etc.?**

**While playing indoors, how often did your child like rough and rowdy games?**

**When being gently rocked or hugged, how often did your child seem eager to get away?**

**When encountering a new activity, how often did your child get involved immediately?**

In the last two weeks...

**When engaged in an activity requiring attention, such as building with blocks, how often did your child tire of the activity relatively quickly?**

**During everyday activities, how often did your child...**

- **...pay attention to you right away when you called to him/her?**
- **...seem to be irritated by tags in his/her clothes?**
- **...become bothered by sounds while in noisy environments?**
- **...seem full of energy, even in the evening?**

**While in a public place, how often did your child seem afraid of large, noisy vehicles?**

**During everyday activities, how often did your child...**

- **...pay attention to you right away when you called to him/her?**
- **...seem to be irritated by tags in his/her clothes?**
- **...become bothered by sounds while in noisy environments?**
- **...seem full of energy, even in the evening?**

**While in a public place, how often did your child seem afraid of large, noisy vehicles?**

**When playing outdoors with other children, how often did your child seem to be one of the most active children?**

**When told “no”, how often did your child...**

- **...stop the forbidden activity?**
- **...become sadly tearful?**

**Following an exciting activity or event, how often did your child seem to feel down or blue?**

**While playing indoors, how often did your child run through the house?**

**Before an exciting event (such as receiving a new toy), how often did your child get very excited about getting it?**

**When s/he asked for something and you said “no”, how often did your child have a temper tantrum?**

**When asked to wait for a desirable item (such as ice cream), how often did your child wait patiently?**

**When being gently rocked, how often did your child smile?**

**While being held on your lap, how often did your child mold to your body?**

**When a familiar adult, such as a relative or friend, visited your home, how often did your child want to interact with the adult?**

**When asked to do so, how often was your child able to be careful with something breakable?**

**When visiting a new place, how often did your child not want to enter?**

**When s/he was upset, how often did your child...**
- **...cry for more than 3 minutes, even when being comforted?**
- **...become easily soothed?**

**When you were busy, how often did your child find another activity to do when asked?**

**When around large gatherings of familiar adults or children, how often did your child enjoy playing with a number of different people?**
