---
title: "PLAY & Learning Across a Year"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

## FAQ about scheduling and recruitment

##### Mom says the child hears other languages. What factors decide if the child can participate?
- The main consideration is what language(s) are spoken to the child in the home, and what language(s) does the mom ever speak to the child (at home, while shopping, elsewhere, etc.). If the child is spoken to at home or by the mom in anything other than English and/or Spanish they are not eligible.

- Allowable exceptions:
  * Sign language (as it is not a verbal language) is permissible for the child to hear.
  * Learning a handful of words, conventional phrases, or expressions (e.g., "good morning," "thank you," "hello," religious terms, food) in another language is allowed. There is no hard cap, but 10 or fewer words is probably fine.
  * If the child hears languages other than English/Spanish **outside the home** (at daycare, visiting family, etc.; not from the mom), that is allowed.
  * If the child occasionally hears other languages while at home, **from someone who does not live there or infrequently visits** (e.g., aunt visits once a week or so), that is allowed.

- Disqualifications:
  * If the child hears other languages while at home, **from someone who lives there** (e.g., grandma lives with them) or **visits frequently** (e.g., nanny comes 3-4 days a week, cousin comes after school every day), that would make them ineligible. That is, they are experiencing regular input (3-4 days) and would not qualify.
  * Even if the mom or household member is just "exposing" them to the language (letting them hear it as an experience, familiarizing them to it, etc.), that would make them ineligible. The child can't distinguish "exposure" from actually learning it.
  * If the child (because of any language experiences) speaks a language other than English/Spanish, they cannot participate. That is, even if mom doesn't speak that language and no one at home speaks that language, the child may naturally speak it during the home visit, so they are ineligible.

The scientific rationale is that all sessions will be transcribed, and PLAY only has English and Spanish transcribers. The mom or child cannot be artificially asked to speak in only some languages; we want their natural speech. The above rules are complicated, but were designed to allow more families to participate, instead of excluding them with simpler rules.

#### What if during the recruitment call, the mom mentions a child impairment (cognitive, motor, language, visual)—referral, diagnosis, concern, etc?
If the mom mentions anything about a child impairment, ask for clarification about the current status during the recruitment call. If the child is currently seeing or was referred to a specialist or a medical professional is concerned about their development in relation to a cognitive, motor, speech, learning, visual, behavioral, hearing delay or condition, then the child is not eligible for PLAY. It is critical to ask for clarification prior to enrolling them and doing the Demographic Questionnaire.


##### If mom asks if she needs to be alone during the study, and if father/aunt/nanny/etc. can be anywhere at home during the study  
<say>For the first 90 minutes of this study, we are interested in how mothers and children interact. It should only be you and your child during the first half of our visit. If father/aunt/nanny/etc isn’t able to stay out of the home for the full time that we’re there, they can come back for the last hour. But we want you to be the one that answers the questionnaires.</say> 

##### How far can we go to visit a family for a home visit?
 - It is up to the PI and research team what the maximum distance they want to travel is. Depending on the location, some sites may have longer commute times than others.   

##### Are travel expenses (i.e. public transportation or gas) reimbursed?
 - Please speak with your site PI about what travel expenses can be covered and how to obtain reimbursements.   




##### If mom specifically says that the father/anyone works at home and that it’s inconvenient for them to leave

<say>We really want just mom and child in the house during the first half of the visit. If there is a separate room with a door that the child never goes into (and that the father/person wouldn’t leave anytime during the first half of the visit), then it’s ok. But, if the father/person would be in an open room or somewhere your child has access to, we need to find a time when it's just you and your child for that first half.</say> 


##### What if phone questionnaire was not done before home visit?

* Ideally this should be completed before the visit, over the phone, because some of these questions will ensure eligibility of the family to participate  
* Complete it right before the other questionnaires in the home but _do not record this portion_

##### Mom says she needs to ask child’s father about participating
<say>Sure, we will send you an email about what the study is about and include the permission forms that we will have you sign. Would it be alright if we called you back in 2-3 days?</say>   

* Arrange a time to call back.

##### Parent unsure about sharing videos
<say>Video data like this is incredibly valuable for us and other developmental researchers around the country.  
To participate in this study, we would ask to be able to share the video with other developmental researchers, like the professor who runs our lab. The goal is to make what we learn from you and your baby available to other scientists. On our permission forms, there are two levels of permission and you can indicate whatever you are comfortable with. If you want, we can send you an email with a copy of the form for you to look over. Can I give you a call back in 2-3 days to see if you would be interested in participating?</say>   

* If parent still does not want to share video, _**do not schedule them**_.

##### What if I want to schedule someone as a "pilot" session who does not meet inclusion criteria?
- It's okay to run a few practice sessions as a new experimenter. Treat everything from scheduling through data collection and clean up exactly as a normal session. Upload all videos to Databrary and mark the session as pilot in the post-visit notes. Quality assurance and feedback will still be given.
- Give the mother the participant payment for a pilot visit exactly like a real visit.

##### What happens if I need to reschedule a visit, but I haven't been to their home yet?
- Make sure the child still will be within the age window (within 1 month of 12, 18, or 24 months) on the new test date. Otherwise, you can keep their contact information to schedule them later for the next age window.
- Update the Test Date on Databrary for that session. Keep the same subject number.
- You DO NOT need to send participant payment for the rescheduled or canceled visit.

##### What happens if I need to reschedule a visit while I'm on a home visit (because something happened with equipment or participants)
- Try to reschedule for within the next 1-2 days if possible.
- Make sure the child still will be within the age window (within 1 month of 12, 18, or 24 months) on the new test date.
- The Test Date on Databrary should be the date the 1-hour natural play was done (so updated it if needed). Keep the same subject number.
- Give the mother participant payment in full amount on both visits.

---
