---
title: ''
---

## HOME ENVIRONMENT

I am going to read you statements about your home. 
Please answer which statements are True and which one’s are False. 
For some statements you may feel that they are True some of the time but not always.
Determine whether the statement is True or False the majority of the time and answer accordingly.

**C1. There is very little commotion in our home.**

TRUE _____  FALSE _____

**C2. We can usually find things when we need them.**

TRUE _____  FALSE _____

**C3. We almost always seem to be rushed.**

TRUE _____  FALSE _____

**C4. We are usually able to “stay on top of things".**

TRUE _____  FALSE _____

**C5. It’s a real “zoo” in our home.**

TRUE _____  FALSE _____

**C6. At home we can talk to each other without being interrupted.**

TRUE _____  FALSE _____

**C7. There is often a fuss going on at our home.**

TRUE _____  FALSE _____

**C8. Our home is a good place to relax.**

TRUE _____  FALSE _____

**C9. The telephone takes up a lot of our time at home.**

TRUE _____  FALSE _____

**C10. The atmosphere in our home is calm.**

TRUE _____  FALSE _____

**C11. We have an evening bed time routine with [target child].**

TRUE _____  FALSE _____
