
### 1.1 Llamada Inicial ( opción 1/3)

<say>Hola, ¿puedo hablar con [MAMÁ]? Mi nombre es [NOMBRE DE PERSONA QUE LLAMA] y estoy llamando de [LAB] por un estudio en el cual estamos observando como madres e hijos interactúan en el hogar. Lo visitaríamos en su hogar y usted recibiría $25 por su participación. ¿Puedo contarle sobre el estudio?
Primero tengo unas preguntas para ver si usted y [NIÑO] califican para participar en este estudio.</say>  
<br>

<say>¿[NIÑO] tiene hermanos?</say>  

<indent>→ En caso de si: finalice la llamada. </indent> <say>Actualmente para este estudio estamos sólo incluyendo a hijos únicos. ¿Estaría bien si les contactamos para otros estudios más adelante?</say>  
<indent>→ En caso de no: continúe</indent>  
<br>

<say>¿En que idioma(s) le habla usted a [NIÑO]?</say>  
<indent>→ Si no es INGLES o ESPAÑOL finalice la llamada.</indent><say>Para controlar diferencias de comunicación, estamos buscando familias que hablen primariamente inglés o español. ¿Estaría bien si les contactamos para otros estudios más adelante?</say>  
<indent>→ En caso de si: continúe</indent>  
<br>

<say>¿Nació [NIÑO] en su fecha de termino?</say> (En caso de no: <say>Cuántas semanas y/o días antes/después de su fecha de termino nació?</say>)  
<indent>→ Si nació más de 4 semanas antes: finalice la llamada.</indent><say>Actualmente para este estudio estamos buscando a niños que hayan nacido de termino. ¿Estaría bien si les contactamos para otros estudios más adelante?</say>  
<indent>→ Si nació de termino (37-41 semanas): continúe</indent>  
<br>

<say>¿Ha sido [NIÑO] diagnosticado con alguna discapacidad (cognitiva, auditiva, visual, o motora)?</say>  
<indent>→ En caso de si: finalice la llamada.</indent> <say>Actualmente para este estudio estamos buscando a niños con desarrollo típico. ¿Estaría bien si les contactamos para otros estudios más adelante?</say>  
<indent>→ En caso de no: continúe</indent>  
<br>

<say>En este estudio estamos interesados en aprender sobre las experiencias rutinarias que los bebés tienen en sus hogares. Un investigador lo visitará a usted y a [NIÑO] en su hogar por aproximadamente 3 horas. Lo gravaremos en video a usted y [NIÑO] por 1 hora mientras ustedes continúan con sus actividades rutinarias. A continuación, le haremos preguntas de las habilidades y rutina de [NIÑO]. También le pediremos recorrer su hogar mientras grabamos el espacio. Por su participación los compensaremos con $25 al final de la sesión. Los datos recolectados en este estudio son valiosos y serán colocados en una biblioteca privada en internet a la cual sólo tienen acceso los investigadores autorizados. El propósito es compartir los datos con expertos en el área para que los científicos puedan aprender más sobre el desarrollo infantil. ¿Le interesaría participar en este estudio con [NIÑO]?</say>  
<indent>→ En caso de no querer participar en el estudio o estar dispuesto a compartir los videos en Databrary: finalice la llamada. <say>Bueno, gracias. ¿Podemos contactarles para otros estudios?</say></indent>  
<indent>→ En caso de si: continúe.</indent>  
<br>

<say>¡Genial! Debido a que estamos interesados en las rutinas de madres e hijos, nos gustaría encontrar un día y hora en el cual podamos observar sólo a usted y [NIÑO] en su hogar. Seria bueno si pudiéramos programar la visita a una hora que no sea durante el horario de comidas y cuando [NIÑO] esta generalmente despierto. ¿Hay algún día y hora que sea conveniente para usted donde se cumplan estos criterios?</say>  
<indent>→ Si en la fecha en la cual están disponibles el bebé ya esta fuera de el rango de edad:</indent> <say>Para este estudio estamos interesados en estudiar grupos de edad específicas: 12-, 18, y 23- meses. ¿Estaría bien si les contactamos en XX meses para ver si [NIÑO] puede participar entonces?</say>  
<indent>→ En caso de si: continúe.</indent>  
<br>

<say> Entonces tenemos agendada la visita para el día [FECHA] a las [HORA]. La llamaremos el día anterior /el viernes anterior (si la visita es un lunes) para confirmar que aun están disponibles para a la visita. Por ultimo, tenemos un cuestionario que solo tomará 5 minutos necesitamos completar antes de nuestra visita. Podemos preguntarle las preguntas ahora o cuando llamemos para confirmar el estudio. ¿Qué prefiere usted?</say>

<indent>→ En caso de que madre tenga tiempo para responder las preguntas: continúe con el cuestionario telefónico.</indent>  
<say>Excelente, que tenga un buen día!</say>
