---
title: "site_NYINI"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
---

```{r setup, include=FALSE}
source("R/site_data.R")
install.packages("googlesheets4")
install.packages("googledrive")
library(googlesheets4)
library(googledrive)

id_trackingsheet <- as_sheets_id("1V9RuZJNRN4lehLzRSWO0MqVclsXPw7Z-Lxq-VQOvM-A")
DataCollectionTraining <- read_sheet(ss = id_trackingsheet, sheet = "DataCollectionTraining")

```

library(googlesheets)
suppressMessages(library(dplyr))


<br>

# Site-specific information for NYUNI

#### Site PI
DataCollectionTraining

#### Researchers



Master checklist: 
* BRANY reliance 
* BRANY subcontract
* BRANY subaward Consent forms CITI for all researchers 
* Recruitment materials
   * Website for parents
   * BRANY-approved flyer
   * Recruitment targets
* Collection materials (shipped to site) 
* Training:
   * Materials training 
   * Overview & DB training 
   * Video training 
   * Forms & Cleanup training 
   * Pilot collection and feedback 
* Collection start to finish
   * Heavy 3-4 QA pass 
   * Light QA for rest (except two more HQAs at midpoint and towards the end)
   * Collection complete



## Participant recruitment targets

- Age target: 10 (12-month olds) + 10 (18-month olds) + 10 (24-month olds)
- Language target (as defined by languages spoken in the home OR languages spoken to the child ): x Spanish, y English
- Education target (highest achievement): HS + 

Data Collection Site Trainings
https://docs.google.com/document/d/1l0ylO88SUmzIpuyfcQ0vSyow8icqUZ8jd5OG06kcdA0/edit

<!--Start info button-->
<div class="popup" onclick="myFunction()">Click me! &#9432;
  <span class="popuptext" id="myPopup">A Simple Popup!</span>
</div>
<script>
// When the user clicks on div, open the popup
function myFunction() {
  var popup = document.getElementById("myPopup");
  popup.classList.toggle("show");
}
</script>
<!--End info button-->
