---
title: ''
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

## TOYS AND MATERIALS

**T1. Does [CHILD] HAVE the following toys at home?**

|                                               |  Yes | No |
|-----------------------------------------------|------|----|
| Action figures |      |    |
| Baby stroller | | |
| Baby walker |||
| Balls |||
| Buildings such as school, farm, castle |||
| Busy box/Activity Center |||
| Children's books |||
| Cleaning set |||
| Crayons, coloring books, paints |||
| Doctor set |||
| Dolls |||
| Dress up clothes or costumes (like princess or Spiderman costumes; adult-like shoes) |||
| ExerSaucer |||
| Geometric shapes |||
| Interlocking blocks (Duplo/Lego blocks that fit together) |||
| Jolly jumper / bouncer ||| 
| Kitchen sets, tea sets, and/or food sets |||
| Makeup or grooming toys (brush, comb, mirror, makeup) |||
| Model size play sets for dolls (doll house) |||
| Musical instruments |||
| Nesting/stacking toys |||
| Playdoh or clay |||
| Pocketbooks, purse, glasses. |||
| Push toy (ball popper, lawn mower) |||
| Puzzles |||
| Ride toys (bike, scooter, rocking horse, car to sit in) |||
| Shape sorter |||
| Soft toys like teddy bear, stuffed animals or puppets |||
| Sports equipment (nets, bats, racquets, hockey sticks) |||
| Tools (screwdriver, hammer) |||
| Toy computer |||
| Toy guns and/or swords |||
| Toy phone |||
| Train or roadway sets |||
| Vehicles (cars, trucks, trains and planes) |||

## PETS

**P1. Do you have any pets at home?**

No _____ Yes _____

Please list? ______________________________.

**P2. Do you have any dogs at home?**

No _____ Yes _____ 

- **P2a. How many?** ____________. 

- **P2b. Do they live mainly**:

Indoors _____ Outdoors _____

**P3. Do you have any cats at home?**

No _____ Yes _____ 

- **P3a. How many?** ____________. 

- **P3b. Do they live mainly**:

Indoors _____ Outdoors _____

**P4. Has the number of pets in your home changed since your infant was born?**

No _____ Yes _____ 

Please explain: ______________________________.
