

Child

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62749/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62785/download?inline=true")
```

Also included in this pass are the times when the child is riding a locomotor device or locomotion cannot occur because the child is held

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62751/download?inline=true")
```

and the times child is constrained in child furniture (e.g., a belted chair, highchair, or stroller) OR when locomotion cannot be reliably coded (coded as missing in this pass). 

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62753/download?inline=true")
```


l


```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62761/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62769/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62771/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62773/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62783/download?inline=true")
```


```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62787/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62775/download?inline=true")
```


f


```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62747/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/63330/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/63336/download?inline=true")
```

m


```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62765/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62757/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62759/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62797/download?inline=true")
```

d

r

.




Mom?

l

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62779/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62795/download?inline=true")
```

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/62797/download?inline=true")
```


f

```{r, results='asis'}
write_video_clip_html_SJ("https://nyu.databrary.org/slot/14765/-/asset/63360/download?inline=true")
```


