---
title: "Welcome to your own PLAY page!"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
---

`This page was last updated on <date>`

In this page, you will find all information that is specific to your lab. For information that's common to all labs, please explore play-project.org. If you have any questions, always feel free to [contact us](info@play-project.org).  

<hr>

### About your institution
<p>
  <iframe src="https://docs.google.com/spreadsheets/d/1zjbFYQB_f2aGSP0ihSgjvdroX7y2Za0cKzrNOKJZry0/pubhtml/sheet?headers=false&amp;gid=2039514086&amp;range=C6:D12" width="700" height="350" frameborder="0" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">
  </iframe>
</p>

<hr>

### Training, IRB, and materials
<p>
  <iframe src="https://docs.google.com/spreadsheets/d/1zjbFYQB_f2aGSP0ihSgjvdroX7y2Za0cKzrNOKJZry0/pubhtml/sheet?headers=false&amp;gid=2039514086&amp;range=C13:D18" width="700" height="350" frameborder="0" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">
  </iframe>
</p>

<hr>

### Training status 

<!-- Get this info from:
https://docs.google.com/spreadsheets/d/1V9RuZJNRN4lehLzRSWO0MqVclsXPw7Z-Lxq-VQOvM-A/edit#gid=534220408 -->

Collection IRB status: `approved`  
Collection training 1: `people and dates`  
Collection training 2: `people and dates`   
Collection training 3: `people and dates`   
Training video status: `Orit's table`  

Coding IRB status: `approved`  
Coding training 1: `people and dates`  
Coding training 2: `people and dates`   
Coding training 3: `people and dates`   
Training video status: `Orit's table`  

<hr>

### Recruitment materials 
Website for parents: [www.anhourinthelife.org](http://www.anhourinthelife.org)  
BRANY-approved flyer: [click here to download]()
Participant recruitment targets  

- Age target:  
     - 12-month olds: 10  
     - 18-month olds: 10   
     - 24-month olds: 10  
- Language target  
(languages spoken in the home OR to the child )
     - `x` Spanish  
     - `y` English   
- Education target (highest achievement)
     - did we 
     - decide on this? 
     
<hr>

### Your Data Collection status 
Collection QA status: `table`  
Collection links:  
 - Google form (checklist)  
 - Kobotoolbox (link)  

<p>
  <iframe src="https://docs.google.com/spreadsheets/d/1zjbFYQB_f2aGSP0ihSgjvdroX7y2Za0cKzrNOKJZry0/pubhtml/sheet?headers=false&amp;gid=2039514086&amp;range=C23:D28" width="700" height="350" frameborder="0" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">
  </iframe>
</p>


<hr>

### Your Data Coding status 
Coding folder location: `box folder`
Coding QA status: `table`  

<p>
  <iframe src="https://docs.google.com/spreadsheets/d/1zjbFYQB_f2aGSP0ihSgjvdroX7y2Za0cKzrNOKJZry0/pubhtml/sheet?headers=false&amp;gid=2039514086&amp;range=C23:D28" width="700" height="350" frameborder="0" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">
  </iframe>
</p>

<hr>

### End of demo text

<hr>
